name: Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
#
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: Save Google Cloud credentials to file
        run: echo "$GOOGLE_CREDENTIALS" | tr -d '\n' > gcloud.json

      - name: Authenticate with Google Cloud CLI
        run: gcloud auth activate-service-account --key-file=gcloud.json

      - name: Terraform Init
        run: terraform init
        env:
          GOOGLE_CREDENTIALS: ${{secrets.GOOGLE_CREDENTIALS}}

      - name: Terraform Plan
        run: TF_LOG=DEBUG terraform plan -out=tfplan -lock=false -input=false -no-color -var="google_credentials=gcloud.json"
        working-directory: ${{ github.workspace }}
        env:
          TF_LOG: DEBUG
          TF_VAR_credentials: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Terraform Apply
        run: terraform apply -auto-approve -lock=false tfplan
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}


      - name: Test Port Access
        run: |
          external_ip=$(terraform output external_ip | tr -d '"')
          echo External IP: $external_ip
          nc -zvw60 $external_ip 80
